

INSERT INTO `piezas` (`id`, `imagen`, `pieza`, `serie`, `marca`, `infoadicional`, `idsucursal`, `idmodelo`, `created_at`, `updated_at`) VALUES
(1, 'imagenespiezas/bujehorquillaA1SYDchico.jpg', 'Buje Horquilla', '191-407-182', 'SYD', 'Chico, Inferior', 2, 1, '', ''),
(2, 'imagenespiezas/bujehorquillaA1SYDgrande.jpg', 'Buje Horquilla', '1J0-407.181.A', 'SYD', 'Grande, Inferior', 2, 1, '', ''),
(3, 'imagenespiezas/buje horquilla A1 HUAT grande.jpg', 'Buje Horquilla', 'PHAK-4028', 'HUAT', 'grande, Inferior', 2, 1, '', ''),
(4, 'imagenespiezas/disco freno A1 ruville.png', 'Disco Freno', 'BRR 3705 10', 'RUVILLE', 'Solido, Trasero', 2, 1, '', ''),
(5, 'imagenespiezas/disco freno A1 cano brake.png', 'Disco Freno', '2292', 'CANO BRAKE', '', 2, 1, '', ''),
(6, 'imagenespiezas/filtro aceite a1.png', 'Filtro Aceite', 'OF-6103', 'INTERFIL', '', 2, 1, '', ''),
(7, 'imagenespiezas/horquilla A1 L.jpg', 'Horquilla', '1526037', 'SYD', 'Inferior L', 2, 1, '', ''),
(8, 'imagenespiezas/horquilla A1 R.jpg', 'Horquilla', '1526038', 'SYD', 'Inferior R', 2, 1, '', ''),
(9, 'imagenespiezas/junta homocinetica A1.jpg', 'Junta Homocinetica', 'CV-328', 'SYD', 'Ext 36 Int 27, Lado Rueda', 2, 1, '', ''),
(10, 'imagenespiezas/Kit Clutch A1.png', 'Kit Clutch', '602 0001 00', 'LUK', '', 2, 1, '', ''),
(11, 'imagenespiezas/maza rueda trasera a1.jpg', 'Maza Rueda', '2326003', 'SYD', 'Trasera', 2, 1, '', ''),
(12, 'imagenespiezas7maza rueda delantera a1.jpg', 'Maza Rueda', '2326001', 'SYD', 'Delantera', 2, 1, '', ''),
(13, 'imagenespiezas/rotula inferior R A1.jpg', 'Rótula', '1026008', 'SYD', 'Inferior R', 2, 1, '', ''),
(14, 'imagenespiezas/rotula inferior L A1.jpg', 'Rótula', '1026009', 'SYD', 'Inferior L', 2, 1, '', ''),
(15, 'imagenespiezas/soporte motor DAI A1 Torsion.png', 'Soporte Motor', '7058', 'DAI', 'Torsión', 2, 1, '', ''),
(16, 'imagenespiezas/soporte motor DAI A1 Frontal R.png', 'Soporte Motor', '7057-H', 'DAI', 'Frontal Derecho', 2, 1, '', ''),
(17, 'imagenespiezas/soporte motor DAI A1 Transmisio.png', 'Soporte Motor', '7060', 'DAI', 'Estándar Transmisión', 2, 1, '', ''),
(18, 'imagenespiezas/soporte motorEAGLEBHPA1Torsion.png', 'Soporte Motor', '1564', 'EAGLE BHP', 'Torsión', 2, 1, '', ''),
(19, 'imagenespiezas/soporte motor EAGLE BHP T.png', 'Soporte Motor', '1565', 'EAGLE BHP', 'Estándar Transmisión', 2, 1, '', ''),
(20, 'imagenespiezas/soporte motor EAGLE BHP FR.png', 'Soporte Motor', '1330H', 'EAGLE BHP', 'Frontal Derecho', 2, 1, '', ''),
(21, 'imagenespiezas/terminal direccion A1 eR.jpg', 'Terminal Dirección', '6Q0-422-812', 'SYD', 'Exterior R', 2, 1, '', ''),
(22, 'imagenespiezas/terminal direccion A1 eL.jpg', 'Terminal Dirección', '6Q0-422-811', 'SYD', 'Exterior L', 2, 1, '', ''),
(23, 'imagenespiezas/tornillo estabilizador A1 SYD.jpg', 'Tornillo Estabilizador', '2126004', 'SYD', 'Delantero', 2, 1, '', ''),
(24, 'imagenespiezas/tornillo estabilizador A1 HUAT.jpg', 'Tornillo Estabilizador', 'PHAK.3022', 'HUAT', 'Delantero', 2, 1, '', ''),
(25, 'imagenespiezas/bujehorquillaA1SYDchico.jpg', 'Buje Horquilla', '191-407-182', 'SYD', 'Chico, Inferior', 5, 1, '', ''),
(26, 'imagenespiezas/bujehorquillaA1SYDgrande.jpg', 'Buje Horquilla', '1J0-407.181.A', 'SYD', 'Grande, Inferior', 3, 1, '', ''),
(27, 'imagenespiezas/buje horquilla A1 HUAT grande.jpg', 'Buje Horquilla', 'PHAK-4028', 'HUAT', 'grande, Inferior', 5, 1, '', ''),
(28, 'imagenespiezas/disco freno A1 ruville.png', 'Disco Freno', 'BRR 3705 10', 'RUVILLE', 'Solido, Trasero', 3, 1, '', ''),
(29, 'imagenespiezas/disco freno A1 cano brake.png', 'Disco Freno', '2292', 'CANO BRAKE', '', 5, 1, '', ''),
(30, 'imagenespiezas/filtro aceite a1.png', 'Filtro Aceite', 'OF-6103', 'INTERFIL', '', 3, 1, '', ''),
(31, 'imagenespiezas/horquilla A1 L.jpg', 'Horquilla', '1526037', 'SYD', 'Inferior L', 5, 1, '', ''),
(32, 'imagenespiezas/horquilla A1 R.jpg', 'Horquilla', '1526038', 'SYD', 'Inferior R', 3, 1, '', ''),
(33, 'imagenespiezas/junta homocinetica A1.jpg', 'Junta Homocinetica', 'CV-328', 'SYD', 'Ext 36 Int 27, Lado Rueda', 5, 1, '', ''),
(34, 'imagenespiezas/Kit Clutch A1.png', 'Kit Clutch', '602 0001 00', 'LUK', '', 3, 1, '', ''),
(35, 'imagenespiezas/maza rueda trasera a1.jpg', 'Maza Rueda', '2326003', 'SYD', 'Trasera', 5, 1, '', ''),
(36, 'imagenespiezas/maza rueda delantera a1.jpg', 'Maza Rueda', '2326001', 'SYD', 'Delantera', 3, 1, '', ''),
(37, 'imagenespiezas/rotula inferior R A1.jpg', 'Rótula', '1026008', 'SYD', 'Inferior R', 5, 1, '', ''),
(38, 'imagenespiezas/rotula inferior L A1.jpg', 'Rótula', '1026009', 'SYD', 'Inferior L', 3, 1, '', ''),
(39, 'imagenespiezas/soporte motor DAI A1 Torsion.png', 'Soporte Motor', '7058', 'DAI', 'Torsión', 5, 1, '', ''),
(40, 'imagenespiezas/soporte motor DAI A1 Frontal R.png', 'Soporte Motor', '7057-H', 'DAI', 'Frontal Derecho', 5, 1, '', ''),
(41, 'imagenespiezas/soporte motor DAI A1 Transmisio.png', 'Soporte Motor', '7060', 'DAI', 'Estándar Transmisión', 3, 1, '', ''),
(42, 'imagenespiezas/soporte motorEAGLEBHPA1Torsion.png', 'Soporte Motor', '1564', 'EAGLE BHP', 'Torsión', 5, 1, '', ''),
(43, 'imagenespiezas/soporte motor EAGLE BHP T.png', 'Soporte Motor', '1565', 'EAGLE BHP', 'Estándar Transmisión', 3, 1, '', ''),
(44, 'imagenespiezas/soporte motor EAGLE BHP FR.png', 'Soporte Motor', '1330H', 'EAGLE BHP', 'Frontal Derecho', 5, 1, '', ''),
(45, 'imagenespiezas/terminal direccion A1 eR.jpg', 'Terminal Dirección', '6Q0-422-812', 'SYD', 'Exterior R', 3, 1, '', ''),
(46, 'imagenespiezas/terminal direccion A1 eL.jpg', 'Terminal Dirección', '6Q0-422-811', 'SYD', 'Exterior L', 5, 1, '', ''),
(47, 'imagenespiezas/tornillo estabilizador A1 SYD.jpg', 'Tornillo Estabilizador', '2126004', 'SYD', 'Delantero', 3, 1, '', ''),
(48, 'imagenespiezas/tornillo estabilizador A1 HUAT.jpg', 'Tornillo Estabilizador', 'PHAK.3022', 'HUAT', 'Delantero', 5, 1, '', '');
